### ISSUE TITLE
profile input in train_brats.py

### ISSUE THREAD

**Issue by samra-irshad** [zwxu064/RANP#1]
Thanks for sharing the code. Could you tell why did you initialize the `profile_input` on `line 342` in `train_brats.py` with `torch.randn(1, 4, args.spatial_size, args.spatial_size, args.spatial_size).cuda()`? does 1  here represent the batch size ?

**Comment by zwxu064** [comment]
Hi, yes, 1 is batch size.

**Comment by zwxu064** [comment]
> Thanks for sharing the code. Could you tell why did you initialize the `profile_input` on `line 342` in `train_brats.py` with `torch.randn(1, 4, args.spatial_size, args.spatial_size, args.spatial_size).cuda()`? does 1 here represent the batch size ?


Hi, yes, 1 is batch size.
